management.trace.http.enabled: true
management.endpoints.web.exposure.include: httptrace

FTLLoginController:
  authentication:
    mode: LDAP   ## Change to different value to invoke to test against hard coded string.

ldap:
  providerURL: ldap://localhost:10389
  password: secret
  adminPrinciple: uid=admin,ou=system
  userPrinciple: ou=users,ou=system

## To enable SSL switch ssl to enabled
server:
  port: 443
  ssl:
    key-store: classpath:keystore-auth.p12
    key-store-password: 3q@v)dha{M:7A{8?
    keyStoreType: PKCS12
    keyAlias: auth-server
    enabled-protocols: TLSv1.3
  session-timeout: 1800